# docker/docker-compose.yml

version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: company_db

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - OPENAI_API_KEY=your_openai_api_key
      - GCP_PROJECT=your_gcp_project
      - GEMINI_ENDPOINT=your_gemini_endpoint
    depends_on:
      - mongodb

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend
    restart: always
    ports:
      - "8001:8001"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  mongo-data:
